---
- name: "Create a 2048-bit SSH key for user {{item}} in /home/{{item}}/.ssh/id_rsa"
  user:
    name: "{{item}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "/home/{{item}}/.ssh/id_rsa"
  with_items:
    - "{{service_accounts}}"

- name: read out the private keys
  include_tasks: read-keys.yml
  with_items:
    - "{{service_accounts}}"