---
# defaults file for zookeeper
client_port: 2181
init_limit: 5
sync_limit: 2
tick_time: 2000
zookeeper_autopurge_purgeInterval: 1
zookeeper_autopurge_snapRetainCount: 3
zookeeper_cluster_ports: "2888:3888"
zookeeper_max_client_connections: 60